services:
  init-certs:
    image: alpine
    volumes:
      - type: bind
        source: ./certs
        target: /certs
    command: >
      /bin/sh -c "
      echo 'Starting certificate generation...';
      if [ ! -f /certs/server.crt ] || [ ! -f /certs/server.key ]; then
        echo 'Certificates not found, generating...';
        apk add --no-cache openssl &&
        openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes -keyout /certs/server.key -out /certs/server.crt -subj '/CN=boston.local' &&
        echo 'Certificates generated successfully.';
      else
        echo 'Certificates already exist.';
      fi;
      "
  # MariaDB Service
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always

  # WordPress with PHP-FPM Service
  wordpress:
    image: wordpress:php8.3-fpm
    depends_on:
      - db
      - elasticsearch
      - redis
    user: "www-data"
    build: 
      context: .
      dockerfile: Dockerfile.wordpress
    expose: 
      - "9000"
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    restart: always

  # Apache Service
  apache:
    image: bitnami/apache:latest
    depends_on:
      - wordpress
      - init-certs
    build: 
      context: .
      dockerfile: Dockerfile.apache
    env_file:
      - local.env
    volumes:
      - ./wordpress:/var/www/html
      - ./certs:/certs  # Mount the shared volume where certificates are stored
    ports:
      - "80:8080"
      - "443:8443"
    restart: always

  # ElasticSearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always

  # Redis Service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  
  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    restart: always

volumes:
  db_data:
  es_data:
  redis_data:
